--- #YAML:1.0
name: Apache2-Mogile-Dispatch
version: 0.2
author:
  - Nick Gerakines <nick@socklabs.com>
abstract: An Apache2 MogileFS Dispatcher
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
